package api;

import javax.annotation.security.DeclareRoles;
// JAX-RS
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

import org.eclipse.microprofile.auth.LoginConfig;
import org.eclipse.microprofile.openapi.annotations.Components;
import org.eclipse.microprofile.openapi.annotations.OpenAPIDefinition;
import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
import org.eclipse.microprofile.openapi.annotations.enums.SecuritySchemeIn;
import org.eclipse.microprofile.openapi.annotations.enums.SecuritySchemeType;
import org.eclipse.microprofile.openapi.annotations.info.Info;
import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.eclipse.microprofile.openapi.annotations.security.SecurityScheme;
import org.eclipse.microprofile.openapi.annotations.tags.Tag;

@ApplicationPath("/")

@LoginConfig(authMethod = "MP-JWT", realmName = "jwt-jaspi")
@DeclareRoles({"user"})

@OpenAPIDefinition(
	    info = @Info(
	        title = "RealWorld example app REST endpoints",
	        version = "1.0",
	        description = "An OpenLiberty using MicroProfile of the RealWorld API Spec: https://github.com/gothinkster/realworld/tree/master/api"
	    ),
	    components = @Components(
	    		securitySchemes = {
	    				@SecurityScheme(securitySchemeName = "Authentication", type=SecuritySchemeType.APIKEY, apiKeyName="Authorization", in = SecuritySchemeIn.HEADER, description="Enter a valid token, generated by creating a user or logging in, to make requests which require authentication. Enter as: Token jwt.token.here")
	    		},
	    		schemas = {
	    				@Schema(name="authenticationExample", type = SchemaType.OBJECT, example = 
	    						"{\n"
	    						+ "  \"user\":{\n"
	    						+ "    \"email\": \"jake@jake.jake\",\n"
	    						+ "    \"password\": \"jakejake\"\n"
	    						+ "  }\n"
	    						+ "}"),
	    				@Schema(name="registrationExample", type = SchemaType.OBJECT, example = 
								"{\n"
								+ "  \"user\":{\n"
								+ "    \"username\": \"Jacob\",\n"
								+ "    \"email\": \"jake@jake.jake\",\n"
								+ "    \"password\": \"jakejake\"\n"
								+ "  }\n"
								+ "}"),
	    				@Schema(name="updateExample", type = SchemaType.OBJECT, example = 
								"{\n"
								+ "  \"user\":{\n"
								+ "    \"email\": \"jake@jake.jake\",\n"
								+ "    \"bio\": \"I like to skateboard\",\n"
								+ "    \"image\": \"https://i.stack.imgur.com/xHWG8.jpg\"\n"
								+ "  }\n"
								+ "}"),
	    				@Schema(name="userExample", type = SchemaType.OBJECT, example = 
								"{\n"
								+ "  \"user\": {\n"
								+ "    \"email\": \"jake@jake.jake\",\n"
								+ "    \"token\": \"jwt.token.here\",\n"
								+ "    \"username\": \"jake\",\n"
								+ "    \"bio\": \"I work at statefarm\",\n"
								+ "    \"image\": null\n"
								+ "  }\n"
								+ "}"),
	    				@Schema(name="multipleArticlesExample", type = SchemaType.OBJECT, example = 
								"{\n"
								+ "  \"articles\":[{\n"
								+ "    \"slug\": \"how-to-train-your-dragon\",\n"
								+ "    \"title\": \"How to train your dragon\",\n"
								+ "    \"description\": \"Ever wonder how?\",\n"
								+ "    \"body\": \"It takes a Jacobian\",\n"
								+ "    \"tagList\": [\"dragons\", \"training\"],\n"
								+ "    \"createdAt\": \"2016-02-18T03:22:56.637Z\",\n"
								+ "    \"updatedAt\": \"2016-02-18T03:48:35.824Z\",\n"
								+ "    \"favorited\": false,\n"
								+ "    \"favoritesCount\": 0,\n"
								+ "    \"author\": {\n"
								+ "      \"username\": \"jake\",\n"
								+ "      \"bio\": \"I work at statefarm\",\n"
								+ "      \"image\": \"https://i.stack.imgur.com/xHWG8.jpg\",\n"
								+ "      \"following\": false\n"
								+ "    }\n"
								+ "  }, {\n"
								+ "    \"slug\": \"how-to-train-your-dragon-2\",\n"
								+ "    \"title\": \"How to train your dragon 2\",\n"
								+ "    \"description\": \"So toothless\",\n"
								+ "    \"body\": \"It a dragon\",\n"
								+ "    \"tagList\": [\"dragons\", \"training\"],\n"
								+ "    \"createdAt\": \"2016-02-18T03:22:56.637Z\",\n"
								+ "    \"updatedAt\": \"2016-02-18T03:48:35.824Z\",\n"
								+ "    \"favorited\": false,\n"
								+ "    \"favoritesCount\": 0,\n"
								+ "    \"author\": {\n"
								+ "      \"username\": \"jake\",\n"
								+ "      \"bio\": \"I work at statefarm\",\n"
								+ "      \"image\": \"https://i.stack.imgur.com/xHWG8.jpg\",\n"
								+ "      \"following\": false\n"
								+ "    }\n"
								+ "  }],\n"
								+ "  \"articlesCount\": 2\n"
								+ "}"),
	    				@Schema(name="createArticleExample", type = SchemaType.OBJECT, example = 
								"{\n"
								+ "  \"article\": {\n"
								+ "    \"title\": \"How to train your dragon\",\n"
								+ "    \"description\": \"Ever wonder how?\",\n"
								+ "    \"body\": \"You have to believe\",\n"
								+ "    \"tagList\": [\"reactjs\", \"angularjs\", \"dragons\"]\n"
								+ "  }\n"
								+ "}"),
	    				@Schema(name="updateArticleExample", type = SchemaType.OBJECT, example = 
			    				"{\n"
			    				+ "  \"article\": {\n"
			    				+ "    \"title\": \"Did you train your dragon?\"\n"
			    				+ "  }\n"
			    				+ "}"),
	    				@Schema(name="addCommentExample", type = SchemaType.OBJECT, example = 
								"{\n"
								+ "  \"comment\": {\n"
								+ "    \"body\": \"His name was my name too.\"\n"
								+ "  }\n"
								+ "}"),
	    				@Schema(name="multipleCommentsExample", type = SchemaType.OBJECT, example = 
								"{\n"
								+ "  \"comments\": [{\n"
								+ "    \"id\": 1,\n"
								+ "    \"createdAt\": \"2016-02-18T03:22:56.637Z\",\n"
								+ "    \"updatedAt\": \"2016-02-18T03:22:56.637Z\",\n"
								+ "    \"body\": \"It takes a Jacobian\",\n"
								+ "    \"author\": {\n"
								+ "      \"username\": \"jake\",\n"
								+ "      \"bio\": \"I work at statefarm\",\n"
								+ "      \"image\": \"https://i.stack.imgur.com/xHWG8.jpg\",\n"
								+ "      \"following\": false\n"
								+ "    }\n"
								+ "  }]\n"
								+ "}"),
	    				@Schema(name="listOfTagsExample", type = SchemaType.OBJECT, example = 
								"{\n"
								+ "  \"tags\": [\n"
								+ "    \"reactjs\",\n"
								+ "    \"angularjs\"\n"
								+ "  ]\n"
								+ "}")

	    		}
	    ),
	    tags = {
	    		@Tag(name="Login", description = "Endpoints for registration and authentication"),
	    		@Tag(name="User", description = "Endpoints for requests for the current user"),
	    		@Tag(name="Profile", description = "Endpoints for requests for other profiles"),
	    		@Tag(name="Articles", description = "Endpoints for requests for articles"),
	    		@Tag(name="Tags", description = "Endpoints for requests for tags")
	    }
	)

public class ApiApplication extends Application {

}
